set vb t_vb=
if has("gui_win32")
    set guifont=Courier_New:h11:cANSI
endif

if has("gui_gtk2")
    set guifont=Bitstream\ Vera\ Sans\ Mono\ 11
endif

set guioptions-=m   "no menu bar
set guioptions-=T   "no toolbar
set guioptions-=r
set guioptions+=R
"set guioptions+=aM  "have to read about this
set guiheadroom=0   "dont add extra space at bottom
"set lines=29        "try to make a larger window for gui
"set columns=110     "try to make a larger window for gui

if has("mouse")
      set mouse=a                       "modes for mouse selection
      set mousehide                     "hide mouse when typing
      set mousemodel=popup_setpos       "bring up popup rather than selecting
endif
